###
POST http://localhost:8080/moves
Content-Type: application/json

[
  {"x": 0, "y": 0},
  {"x": 1, "y": 0},
  {"x": 1, "y": 3},
  {"x": 0, "y": 3},
  {"x": 0, "y": 0}
]

###
POST http://localhost:8080/locations
Content-Type: application/json

[
  {
    "direction": "EAST",
    "steps": 1
  },
  {
    "direction": "NORTH",
    "steps": 3
  },
  {
    "direction": "EAST",
    "steps": 3
  },
  {
    "direction": "SOUTH",
    "steps": 5
  },
  {
    "direction": "WEST",
    "steps": 2
  }
]
